### ISSUE TITLE
Chaiverse has some issues with pydantic 2.x

### ISSUE THREAD

**Issue by fredi-python** [chai-research/chaiverse#13]
Pydantic is throwing out an error, when using the chaiverse package along side with pydantic 2.x.
Versions below 2.0 worked for me just fine.
The following error occurs:
```
Traceback (most recent call last):
  File "/home/fredi/PycharmProjects/AI3/newthing.py", line 2, in <module>
    from chaiverse.formatters import PromptFormatter
  File "/home/fredi/PycharmProjects/AI3/venv/lib/python3.11/site-packages/chaiverse/formatters.py", line 37, in <module>
    class PygmalionFormatter(PromptFormatter):
  File "/home/fredi/PycharmProjects/AI3/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 92, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "/home/fredi/PycharmProjects/AI3/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 362, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: Field 'memory_template' defined on a base class was overridden by a non-annotated attribute. All field definitions, including overrides, require a type annotation.

For further information visit https://errors.pydantic.dev/2.5/u/model-field-overridden
```

**Comment by SilentShadow1800** [comment]
Hi developers,I’m a long-time Chai.ai user, and I’ve noticed that the Personality Traits and Chat Type options have been missing from the app for quite some time now. These features were very important to me for customizing how bots behave and feel. Without them, many of my bots feel less personal and more repetitive. I know others in the community also miss these options. I’m kindly asking if you could bring them back, or at least give us an update on whether they’re coming back soon.Thank you so much for your work!
